### PR TITLE
Camera Property Overhaul and Expansion

### PR DESCRIPTION
**Pull request by FluxIX**
I've implemented a different interface to the camera properties. I've also integrated the camera property control into the WinForm Demo.

I think there are some other bug fixes as well.

### CODE REVIEW

**Comment by lepipele** [comment]
@FluxIX thanks for the pull request - I have few questions on some stuff, but let me first merge and ask questions later when I fully review code.

I'll also update the article with thank you notice.

**Comment by FluxIX** [comment]
I haven't any questions come back. Are you still reviewing or are there no questions?

**Comment by lepipele** [comment]
Still reviewing; I was looking if I can somehow simplify that Camera Property Controls region.

Also, can you verify that resolution setting is now properly working in C++? I talk about that here:
http://www.codeproject.com/Articles/125478/Versatile-WebCam-C-library#Problem

Previously _cameraMethods.StartCamera() was using width & height at all... but this was supposedly fixed by btnr. On my machine it looks fine, but I was wondering if you took a look at this at all / did anything with it?

Code I am talking about is in Camera.cs@1014 - you'll see comments explaining the code

**Comment by FluxIX** [comment]
I verified the resolution in the C++ code (I have three machines at work currently which this code runs on, and I needed it to run in 640x480 instead of 320x240 for the application I was writing). I needed to fix the resolution to get it to work (I actually also know the color depth selection works as that was a problem I ran into on one of the test machines).

I did not touch the referenced Camera.cs code, but I think it will need to be updated to take into account the color depth (otherwise you get an undebuggable exception indicating you're access memory you shouldn't). It shouldn't be difficult to update though.

**Comment by FluxIX** [comment]
Were there any other questions regarding the contents of the pull request?

**Pull request merged**
